"""
Code execution via the Piston API (https://emkc.org/api/v2/piston).

Piston is free, open-source, and requires no API key. It supports
Python, JavaScript, Java, C++, and many more languages with sandboxed
execution. We use it instead of Judge0 because Judge0's free RapidAPI
tier is extremely limited (50 requests/day).

The execution model used here is competitive-programming style:
user code reads from stdin and writes to stdout. The starter code
generated by the LLM always includes stdin/stdout boilerplate.
"""

import logging
import time
from dataclasses import dataclass, field

import httpx

logger = logging.getLogger(__name__)

PISTON_URL = "https://emkc.org/api/v2/piston/execute"

# Language configs — verify/update versions at https://emkc.org/api/v2/piston/runtimes
LANGUAGE_CONFIG: dict[str, dict] = {
    "python": {
        "language": "python",
        "version": "3.10.0",
        "filename": "solution.py",
    },
    "javascript": {
        "language": "javascript",
        "version": "18.15.0",
        "filename": "solution.js",
    },
    "java": {
        "language": "java",
        "version": "15.0.2",
        "filename": "Main.java",  # Piston requires file named Main.java for Java
    },
    "cpp": {
        "language": "c++",
        "version": "10.2.0",
        "filename": "solution.cpp",
    },
}


@dataclass
class ExecutionResult:
    status: str           # ok | compile_error | runtime_error | time_limit | error
    stdout: str = ""
    stderr: str = ""
    exit_code: int = 0
    execution_time_ms: float = 0.0


@dataclass
class TestCaseResult:
    passed: bool
    stdin: str
    expected: str
    got: str
    status: str           # ok | wrong_answer | runtime_error | compile_error | time_limit
    execution_time_ms: float = 0.0
    stderr: str = ""


async def _run_once(code: str, language: str, stdin: str) -> ExecutionResult:
    """Run code once against a single stdin and return raw result."""
    config = LANGUAGE_CONFIG.get(language)
    if not config:
        return ExecutionResult(status="error", stderr=f"Unsupported language: {language}")

    payload = {
        "language": config["language"],
        "version": config["version"],
        "files": [{"name": config["filename"], "content": code}],
        "stdin": stdin,
        "args": [],
        "compile_timeout": 10_000,
        "run_timeout": 5_000,
        "compile_memory_limit": -1,
        "run_memory_limit": 256_000_000,
    }

    t0 = time.monotonic()
    try:
        async with httpx.AsyncClient(timeout=20.0) as client:
            resp = await client.post(PISTON_URL, json=payload)
            resp.raise_for_status()
            data = resp.json()
    except httpx.TimeoutException:
        return ExecutionResult(status="time_limit", stderr="Execution timed out (network)")
    except httpx.HTTPStatusError as exc:
        return ExecutionResult(status="error", stderr=f"Piston API error: {exc.response.status_code}")
    except Exception as exc:
        return ExecutionResult(status="error", stderr=str(exc))

    elapsed_ms = (time.monotonic() - t0) * 1000

    # Compiled languages (Java, C++) have a compile step
    compile_info = data.get("compile") or {}
    if compile_info.get("code", 0) != 0 or compile_info.get("stderr", ""):
        return ExecutionResult(
            status="compile_error",
            stderr=compile_info.get("stderr", "Compile error"),
            execution_time_ms=elapsed_ms,
        )

    run = data.get("run", {})
    stdout = run.get("stdout", "").rstrip("\n")
    stderr = run.get("stderr", "")
    exit_code = run.get("code", 0)

    if exit_code != 0:
        return ExecutionResult(
            status="runtime_error",
            stdout=stdout,
            stderr=stderr,
            exit_code=exit_code,
            execution_time_ms=elapsed_ms,
        )

    return ExecutionResult(
        status="ok",
        stdout=stdout,
        stderr=stderr,
        exit_code=0,
        execution_time_ms=elapsed_ms,
    )


def _outputs_match(got: str, expected: str) -> bool:
    """Case-sensitive comparison after stripping trailing whitespace per line."""
    def normalise(s: str) -> str:
        return "\n".join(line.rstrip() for line in s.strip().splitlines())

    return normalise(got) == normalise(expected)


async def run_test_cases(
    code: str,
    language: str,
    test_cases: list[dict],
    sample_only: bool = False,
) -> list[TestCaseResult]:
    """
    Run code against a list of test cases and return per-case results.

    Args:
        code:        The user's full solution code (stdin/stdout style).
        language:    One of python | javascript | java | cpp.
        test_cases:  List of {input, expected_output, is_sample}.
        sample_only: If True, only runs cases where is_sample == True.
    """
    cases_to_run = [
        tc for tc in test_cases
        if (not sample_only) or tc.get("is_sample", False)
    ]

    results: list[TestCaseResult] = []
    compile_error_cached: str | None = None  # if first case fails to compile, skip the rest

    for tc in cases_to_run:
        stdin = tc.get("input", "")
        expected = tc.get("expected_output", "").rstrip("\n")

        if compile_error_cached is not None:
            results.append(TestCaseResult(
                passed=False, stdin=stdin, expected=expected, got="",
                status="compile_error", stderr=compile_error_cached,
            ))
            continue

        exec_result = await _run_once(code, language, stdin)

        if exec_result.status == "compile_error":
            compile_error_cached = exec_result.stderr
            results.append(TestCaseResult(
                passed=False, stdin=stdin, expected=expected, got="",
                status="compile_error", stderr=exec_result.stderr,
                execution_time_ms=exec_result.execution_time_ms,
            ))
            continue

        if exec_result.status in ("runtime_error", "time_limit", "error"):
            results.append(TestCaseResult(
                passed=False, stdin=stdin, expected=expected,
                got=exec_result.stdout,
                status=exec_result.status,
                stderr=exec_result.stderr,
                execution_time_ms=exec_result.execution_time_ms,
            ))
            continue

        passed = _outputs_match(exec_result.stdout, expected)
        results.append(TestCaseResult(
            passed=passed,
            stdin=stdin,
            expected=expected,
            got=exec_result.stdout,
            status="ok" if passed else "wrong_answer",
            execution_time_ms=exec_result.execution_time_ms,
            stderr=exec_result.stderr,
        ))

    return results